<?php

namespace Eugene\Blog2Bundle\Repository;

/**
 * post2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class post2Repository extends \Doctrine\ORM\EntityRepository
{
}
